jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev libglib2.0-dev

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install cython buildozer kivy


      - name: Prepare buildozer spec
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/^requirements =.*/requirements = python3,kivy,cython/' buildozer.spec

      - name: Configure Java environment
        run: |
          # Явно задаём пути к Java
          export JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV


      - name: Build APK
        run: buildozer android debug
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-11-jdk-amd64  # дублируем в env
          ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk
          ANDROID_NDK_HOME: $HOME/.buildozer/android/platform/android-ndk
